bootstrap:
  name: bootstrap
  ip: 172.16.1.5
k8s_api_backend:
  - name: master01
    ip: 172.16.1.38
  - name: master02
    ip: 172.16.1.39
  - name: master03
    ip: 172.16.1.40
machine_config_backend: "{{ k8s_api_backend }}"
ingress_secure_backend: "{{ k8s_api_backend }}"
ingress_insecure_backend: "{{ k8s_api_backend }}"
