ocp_cluster_name: ocp_local
ocp_networktype: OVNKubernetes
ocp_release: 4.16.0-okd-scos.0
ocp_client_url: https://github.com/okd-project/okd-scos/releases/download/{{ ocp_release }}/openshift-client-linux-{{ ocp_release }}.tar.gz
ocp_install_url: https://github.com/okd-project/okd-scos/releases/download/{{ ocp_release }}/openshift-install-linux-{{ ocp_release }}.tar.gz
ocp_webserver_coreos_path: /network/repo/scos

ocp_infra_libvirt_network:
  type: network
  source: lab_ocp

ocp_infra_network:
  gateway: 10.0.0.254
  network: 10.0.0.0
  netmask: 255.255.255.0
  nameservers: 10.0.0.1
  domain: ocp.lab
  timesources:
    - 0.nl.pool.ntp.org
    - 1.nl.pool.ntp.org
    - 2.nl.pool.ntp.org
    - 3.nl.pool.ntp.org

ocp_infra:
  hosts:
    - name: svc
      ip: 10.0.0.2
      mac: '52:54:00:00:00:01'
      role: svc
    - name: bootstrap
      mac: '52:54:00:00:00:02'
      ip: 10.0.0.3
      role: bootstrap
    - name: master01
      mac: '52:54:00:00:00:03'
      ip: 10.0.0.4
      role: master
    - name: master02
      mac: '52:54:00:00:00:04'
      ip: 10.0.0.5
      role: master
    - name: master03
      mac: '52:54:00:00:00:05'
      ip: 10.0.0.6
      role: master
    - name: worker01
      mac: '52:54:00:00:00:06'
      ip: 10.0.0.7
      role: worker
    - name: worker02
      mac: '52:54:00:00:00:07'
      ip: 10.0.0.8
      role: worker
