ocp_cluster_name: okd
ocp_networktype: OVNKubernetes
# for details see https://github.com/okd-project/okd/releases
# fedora core-os https://fedoraproject.org/coreos/download?stream=stable#arches
ocp_coreos_url: https://quay.io/repository/

ocp_client_rpms: false
#ocp_release: 4.15.0-0.okd-scos-2024-01-18-223523
#ocp_release: 4.16.0-0.okd-scos-2024-08-21-155613  # broken
ocp_release: 4.16.0-0.okd-scos-2024-09-24-151747

# local registry url = ocp_local_registry/ocp_local_repository/ocp_release
ocp_product_repo: openshift
ocp_local_repo: "{{ ocp_product_repo }}"
# okd remote registry url = ocp_remote_registry/ocp_product_repo/ocp_release_name:ocp_release
ocp_remote_registry: quay.io
ocp_release_name: okd

ocp_client_url: https://github.com/okd-project/okd-scos/releases/download/{{ ocp_release }}/openshift-client-linux-{{ ocp_release }}.tar.gz
ocp_install_url: https://github.com/okd-project/okd-scos/releases/download/{{ ocp_release }}/openshift-install-linux-{{ ocp_release }}.tar.gz
ocp_webserver_coreos_path: /network/repo/scos

efi_secure_boot: false
