- name: Ensure required packages are installed
  ansible.builtin.dnf:
    name: "{{ ocp_svc_loadbalancer_packages }}"
    state: present
  when: ocp_svc_loadbalancer_packages | ansible.builtin.difference(ansible_facts['packages'].keys()) | length > 0

- name: Set haproxy_connect_any flag
  ansible.posix.seboolean:
    name: haproxy_connect_any
    state: true
    persistent: true

- name: Ensure ha-proxy is enabled and started
  ansible.builtin.systemd_service:
    name: haproxy
    enabled: true
    state: started

- name: Ensure haproxy.cfg configuration is present
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: "0644"
  notify:
    - Restart haproxy

- name: Open firewall ports
  ansible.posix.firewalld:
    port: 6443/tcp
    state: enabled
    permanent: true
    immediate: true
    offline: true

- name: Open firewall ports
  ansible.posix.firewalld:
    port: 22623/tcp
    state: enabled
    permanent: true
    immediate: true
    offline: true
