- name: Setup dns
  ansible.builtin.include_tasks:
    file: dns.yml

- name: Setup dhcp
  ansible.builtin.include_tasks:
    file: dhcp.yml

- name: Setup tftp
  ansible.builtin.include_tasks:
    file: tftp.yml

- name: Setup http
  ansible.builtin.include_tasks:
    file: http.yml

- name: Setup loadbalancer
  ansible.builtin.include_tasks:
    file: loadbalancer.yml

- name: Install the packages that I like
  ansible.builtin.dnf:
    name: "{{ ocp_svc_my_prefered_packages }}"
    state: present
  when: "ocp_svc_my_prefered_packages | difference(ansible_facts['packages']) | length > 0"

- name: Update the system
  ansible.builtin.dnf:
    name: "*"
    state: latest
    update_only: true
