all:
  vars:
    cluster: ocp_local
  hosts:
    svc:
      ansible_host: 10.0.0.1
      mac: '52:54:00:00:00:01'
      init: kickstart
      ansible_user: root
      services:
        - bind
        - dhcp
        - tftp
        - http
      virtual: true
    lb:
      ansible_host: 10.0.0.2
      mac: '52:54:00:00:00:02'
      init: kickstart
      ansible_user: root
      virtual: true
    bootstrap:
      ansible_host: 10.0.0.3
      mac: '52:54:00:00:00:03'
      init: ignition
      ansible_user: core
      virtual: true
    master01:
      ansible_host: 10.0.0.4
      mac: '52:54:00:00:00:04'
      init: ignition
      ansible_user: core
      virtual: true
    master02:
      ansible_host: 10.0.0.5
      mac: '52:54:00:00:00:05'
      init: ignition
      ansible_user: core
      virtual: true
    master03:
      ansible_host: 10.0.0.6
      mac: '52:54:00:00:00:06'
      init: ignition
      ansible_user: core
      virtual: true
    worker01:
      ansible_host: 10.0.0.7
      mac: '52:54:00:00:00:07'
      init: ignition
      ansible_user: core
      virtual: true
    worker02:
      ansible_host: 10.0.0.8
      mac: '52:54:00:00:00:08'
      init: ignition
      ansible_user: core
      virtual: true
  children:
    ocp_local:
      hosts:
        svc:
        lb:
        bootstrap:
        master01:
        master02:
        master03:
        worker01:
        worker02:
    svc:
      hosts:
        svc:
      vars:
        role: svc
    loadbalancer:
      hosts:
        lb:
    bootstrap:
      hosts:
        bootstrap:
      vars:
        role: bootstrap
    masters:
      hosts:
        master01:
        master02:
        master03:
      vars:
        role: master
    workers:
      hosts:
        worker01:
        worker02:
      vars:
        role: worker
