- name: Reload firewalld
  ansible.builtin.systemd_service:
    name: firewalld
    state: reloaded

- name: Restart haproxy
  ansible.builtin.systemd_service:
    service: haproxy
    state: restarted
