- name: Add host
  ansible.builtin.add_host:
    name: "{{ host['name'] }}"
    groups: "{{ host['groups'] | default([]) }}"
    ansible_host: "{{ host['ip'] }}"
    ansible_user: "{{ host['user'] }}"
