- name: Delete the iso's
  ansible.builtin.include_tasks:
    file: delete_iso.yml
  when:
    - host in init_vms

- name: Create the iso's
  ansible.builtin.include_tasks:
    file: create_iso.yml
  when:
    - host in init_vms