- name: Setup the iso's
  ansible.builtin.include_tasks:
    file: iso.yml
  loop: "{{ lab_infra['hosts'] }}"
  loop_control:
    loop_var: host

- name: Setup vm's
  ansible.builtin.include_tasks:
    file: vm.yml
  loop: "{{ lab_infra['hosts'] }}"
  loop_control:
    loop_var: host
