- name: Clean up the lab
  ansible.builtin.include_role:
    name: lab
    tasks_from: clean
  when: clean_lab | default(false) | bool

- name: Setup the iso's
  ansible.builtin.include_tasks:
    file: iso.yml
  loop: "{{ lab_infra['hosts'] }}"
  loop_control:
    loop_var: host

- name: Setup vm's
  ansible.builtin.include_tasks:
    file: vm.yml
  loop: "{{ lab_infra['hosts'] }}"
  loop_control:
    loop_var: host

- name: Add vm's to the ansible playbook hosts
  ansible.builtin.include_tasks:
    file: add_host.yml
  loop: "{{ lab_infra['hosts'] }}"
  loop_control:
    loop_var: host
