- name: Clean up the lab
  ansible.builtin.include_role:
    name: lab
    tasks_from: clean
  when: clean_lab | default(false) | bool

- name: Setup the iso's
  ansible.builtin.include_tasks:
    file: iso.yml
  loop: "{{ groups['svc'] + groups['loadbalancer'] }}"
  loop_control:
    loop_var: host
  when:
    - hostvars[host]['virtual'] | bool
    - host in init_vms

- name: Setup vm's
  ansible.builtin.include_tasks:
    file: vm.yml
  loop: "{{ groups['svc'] + groups['loadbalancer'] + groups['masters'] + groups['workers'] + groups['bootstrap'] }}"
  loop_control:
    loop_var: host
  when:
    - hostvars[host]['virtual'] | bool
    - host in init_vms
