- name: Setup the lab
  hosts: localhost
  gather_facts: false
  become: false

  tasks:
    - name: Add localhost to all
      ansible.builtin.add_host:
        name: localhost
        groups:
          - all

    - name: Check init settings and vm's
      ansible.builtin.include_role:
        name: prepare

    - name: Warn about cluster init
      when: init_cluster | default(false) | bool
      ansible.builtin.pause:
        prompt: |-
          Reinitializing cluster: {{ cluster }}
          This means all systems from this cluster will be wiped

    - name: Create vm's
      ansible.builtin.include_role:
        name: lab
      vars:
        lab_infra: "{{ ocp_infra }}"

- name: Configure svc host
  hosts: svc
  gather_facts: false
  become: false
  remote_user: root

  tasks:
    - name: Check init settings and vm's
      ansible.builtin.include_role:
        name: prepare

    - name: Start svc vm
      community.libvirt.virt:
        name: "svc"
        state: running
      delegate_to: localhost

    - name: Wait for system to become reachable
      ansible.builtin.wait_for_connection:

    - name: Gather facts
      ansible.builtin.setup:

    - name: Setup the services on the svc vm
      ansible.builtin.include_role:
        name: ocp_svc

- name: Configure loadbalancer host
  hosts: loadbalancer
  gather_facts: false
  become: false
  remote_user: root

  tasks:
    - name: Check init settings and vm's
      ansible.builtin.include_role:
        name: prepare

    - name: Start svc vm
      community.libvirt.virt:
        name: "svc"
        state: running
      delegate_to: localhost

    - name: Wait for system to become reachable
      ansible.builtin.wait_for_connection:

    - name: Setup loadbalancer
      ansible.builtin.include_role:
        name: ocp_lb

- name: Apply personal preferences
  hosts: loadbalancer,svc
  gather_facts: false
  become: false
  remote_user: root

  tasks:
    - name: Include personal preferences
      ansible.builtin.include_role:
        name: lab
        tasks_from: personal

#    - name: The status of mirror installation is
#      ansible.builtin.debug:
#        msg: Mirroring of the registry will {{ ocp_local_registry | default(false) | ternary("", "NOT!!") }} be performed

#    - name: Install ocp client
#      ansible.builtin.include_role:
#        name: ocp_client
#
#    - name: Setup pxe content
#      ansible.builtin.include_role:
#        name: ocp_pxe_content
#
#    - name: Create ocp image mirror script and secret
#      ansible.builtin.include_role:
#        name: ocp_mirror
#      when: ocp_local_registry | default(false)
#
#    - name: Create ocp ignition files
#      ansible.builtin.include_role:
#        name: ocp_ignition_files
#
#    - name: Create virtual machines
#      ansible.builtin.include_role:
#        name: ocp_vm
