- name: Setup ocp configuration
  hosts: localhost
  connection: local
  become: false
  gather_facts: false

  tasks:
    - name: Add localhost to all
      ansible.builtin.add_host:
        name: localhost
        groups:
          - all
        ansible_user: "{{ lookup('ansible.builtin.env', 'USER') }}"
        ansible_connection: local

    - name: Check init settings and vm's
      ansible.builtin.include_role:
        name: prepare

    - name: The version of the installation
      ansible.builtin.debug:
        msg: We will be installing ocp release {{ ocp_release }} on cluster {{ cluster }}

    - name: Warn about cluster init
      when: init_cluster | default(false) | bool
      ansible.builtin.pause:
        prompt: |-
          Reinitializing cluster: {{ cluster }}
          This means all systems from this cluster will be wiped
          And the local configuration directory deleted
          Press enter to continue

    - name: Setup ocp binaries
      ansible.builtin.include_role:
        name: ocp_binaries

    - name: Prepare the ocp installation
      ansible.builtin.include_role:
        name: ocp_ignition

    - name: Add hosts to inventory
      ansible.builtin.include_role:
        name: lab
        tasks_from: add_host
      loop: "{{ ocp_infra['hosts'] }}"
      loop_control:
        loop_var: host

- name: Download pxe binaries to svc
  hosts: svc
  gather_facts: false
  become: false
  remote_user: root

  tasks:
    - name: Check init settings and vm's
      ansible.builtin.include_role:
        name: prepare

    - name: Start svc vm
      community.libvirt.virt:
        name: "svc"
        state: running
      delegate_to: localhost

    - name: Wait for system to become reachable
      ansible.builtin.wait_for_connection:

    - name: Setup the pxe binaries on the svc vm
      ansible.builtin.include_role:
        name: ocp_pxe_binaries

#      vars:
#        ocp_binaries_assetsdir: hostvars['localhost']['ocp_binaries_assetsdir']
#        ocp_binaries_webdir: hostvars['localhost']['ocp_binaries_webdir']
