- name: Configure the haproxy system
  hosts: loadbalancer
  gather_facts: true
  become: true

  tasks:
    - name: Ensure bootstrap is set
      ansible.builtin.set_fact:
        enable_bootstrap: "{{ enable_bootstrap | default(false) }}"

    - name: Show what bootstrap is set to
      ansible.builtin.debug:
        msg: "enable_bootstrap is set to {{ enable_bootstrap | string }}"

    - name: Gather package facts
      ansible.builtin.package_facts:

    - name: Include variables for haproxy
      ansible.builtin.group_by:
        key: haproxy

    - name: Configure haproxy
      ansible.builtin.include_role:
        name: ocp_lb
      vars:
        ocp_lb_enable_bootstrap: "{{ enable_bootstrap }}"
