- name: Delete the ocp lab
  hosts: localhost
  gather_facts: false
  become: false

  tasks:
    - name: Assert that cluster is set
      ansible.builtin.assert:
        that:
          cluster is defined
        fail_msg: Cluster is not set, did you specify the inventory ?

    - name: Add localhost to all and {{ cluster }}
      ansible.builtin.add_host:
        name: localhost
        groups:
          - all
          - "{{ cluster }}"

    - name: Check init settings and vm's
      ansible.builtin.include_role:
        name: prepare

    - name: Add svc to init_vms
      ansible.builtin.set_fact:
        init_vms: "{{ init_vms | default([]) + groups['svc'] }}"

    - name: Add lb to init_vms
      ansible.builtin.set_fact:
        init_vms: "{{ init_vms | default([]) + groups['loadbalancer'] }}"

    - name: Add cluster nodes to init_vms
      ansible.builtin.set_fact:
        init_vms: "{{ init_vms | default([]) + groups['masters'] + groups['workers'] + groups['bootstrap'] }}"

    - name: Debug vms
      ansible.builtin.debug:
        var: init_vms

    - name: Warn about cluster delete
      ansible.builtin.pause:
        prompt: |-
          Deleting cluster: {{ cluster }}
          This means all systems from this cluster will be wiped
          And the local configuration directory deleted
          Press enter to continue

    - name: Delete vm
      ansible.builtin.include_role:
        name: lab
        tasks_from: delete_vm.yml
      loop: "{{ init_vms }}"
      loop_control:
        loop_var: host

    - name: Delete iso
      ansible.builtin.include_role:
        name: lab
        tasks_from: delete_iso.yml
      loop: "{{ init_vms }}"
      loop_control:
        loop_var: host

    - name: Delete cluster dir
      ansible.builtin.include_role:
        name: ocp_binaries
        tasks_from: dir.yml
