- name: Delete the ocp lab
  hosts: localhost
  gather_facts: false
  become: false

  tasks:
    - name: Check init settings and vm's
      ansible.builtin.include_role:
        name: prepare

    - name: Add svc to init_vms
      ansible.builtin.set_fact:
        init_vms: "{{ init_vms | default([]) + ['svc'] }}"

    - name: Add lb to init_vms
      ansible.builtin.set_fact:
        init_vms: "{{ init_vms | default([]) + ['lb'] }}"

    - name: Add cluster nodes to init_vms
      ansible.builtin.set_fact:
        init_vms: "{{ init_vms | default([]) + ['master01', 'master02', 'master03', 'worker01', 'worker02', 'bootstrap'] }}"

    - name: Warn about cluster delete
      when: init_cluster | default(true) | bool
      ansible.builtin.pause:
        prompt: |-
          Deleting cluster: {{ cluster }}
          This means all systems from this cluster will be wiped
          And the local configuration directory deleted
          Press enter to continue

    - name: Delete vm
      ansible.builtin.include_role:
        name: lab
        tasks_from: delete_vm.yml
      loop: "{{ ocp_infra['hosts'] }}"
      loop_control:
        loop_var: host

    - name: Delete iso
      ansible.builtin.include_role:
        name: lab
        tasks_from: delete_iso.yml
      loop: "{{ ocp_infra['hosts'] }}"
      loop_control:
        loop_var: host

    - name: Delete cluster dir
      ansible.builtin.include_role:
        name: lab
        tasks_from: dir.yml
