---
- name: Clean lab
  hosts: localhost
  remote_user: root
  gather_facts: false
  vars:
    known_hosts_lines:
      - '10.1.0'
      - '172.16.1'
      - '192.168.121'
      - '192.168.122'
      - '.*linux.lab'
      - '.*linux.poc'
      - '.*lab.home'
      - '.*okd.tjako.thuis'
      - katello
      - tower
      - fedora
      - centos
      - rhel
      - kodi
      - localhost
      - ipa
      - geel
      - groen
      - rood
      - pgsql
      - node01
      - node02
      - node03
      - node04
      - node05

  tasks:
    - name: Clean known hosts
      ansible.builtin.lineinfile:
        path: /home/rob/.ssh/known_hosts
        state: absent
        regexp: "^{{ item }}.*"

      loop: "{{ known_hosts_lines }}"
