- name: Configure the bastion system
  hosts: bastion
  gather_facts: true

  tasks:
    - name: Ensure we know what we must install
      ansible.builtin.assert:
        that:
         - ocp_version is defined
         - ocp_version in ['okd','openshift']
        fail_msg: "ocp_version is not propperly set"
    
    - name: Include variables for {{ ocp_version }}
      ansible.builtin.group_by:
        key: "{{ ocp_version }}"

    - name: Install ocp client
      ansible.builtin.include_role:
        name: ocp_client
    
    - name: Create ocp image mirror script and secret
      ansible.builtin.include_role:
        name: ocp_mirror
      when: ocp_local_registry is defined

    - name: Create ocp ignition files
      ansible.builtin.include_role:
        name: ocp_ignition_files

    - name: Create virtual machines
      ansible.builtin.include_role:
        name: ocp_vm
