- name: Delete the ocp lab
  hosts: localhost
  gather_facts: false
  become: false

  tasks:
    - name: Ensure cluster is set
      ansible.builtin.set_fact:
        cluster: "{{ cluster | default('ocp_local') }}"

    - name: Set all init to true
      ansible.builtin.set_fact:
        init_svc: true
        init_lb: true
        init_cluster: true

    - name: Load vars from group {{ cluster }}
      ansible.builtin.group_by:
        key: "{{ cluster }}"

    - name: Ensure all vm's are included
      ansible.builtin.include_role:
        name: ocp_infra
        tasks_from: run.yml

    - name: Warn about cluster delete
      when: init_cluster | default(true) | bool
      ansible.builtin.pause:
        prompt: |-
          Deleting cluster: {{ cluster }}
          This means all systems from this cluster will be wiped
          And the local configuration directory deleted
          Press enter to continue

    - name: Delete vm
      ansible.builtin.include_role:
        name: ocp_infra
        tasks_from: delete_vm.yml
      loop: "{{ ocp_infra['hosts'] }}"
      loop_control:
        loop_var: host

    - name: Delete iso
      ansible.builtin.include_role:
        name: ocp_infra
        tasks_from: delete_iso.yml
      loop: "{{ ocp_infra['hosts'] }}"
      loop_control:
        loop_var: host

    - name: Delete cluster dir
      ansible.builtin.include_role:
        name: ocp_infra
        tasks_from: dir.yml
