- name: Reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Restart named
  ansible.builtin.systemd_service:
    name: named
    state: restarted

- name: Restart dhcpd
  ansible.builtin.systemd_service:
    name: dhcpd
    state: restarted

- name: Restart httpd
  ansible.builtin.systemd_service:
    name: httpd
    state: restarted

- name: Reload firewalld
  ansible.builtin.systemd_service:
    name: firewalld
    state: reloaded
