- name: Set init_vms
  ansible.builtin.set_fact:
    init_vms: []

- name: Add svc to init_vms
  ansible.builtin.set_fact:
    init_vms: "{{ init_vms + ['svc'] }}"
    clean_lab: true
  when: init_svc | default(false) | bool

- name: Add lb to init_vms
  ansible.builtin.set_fact:
    init_vms: "{{ init_vms + ['lb'] }}"
    clean_lab: true
  when: init_lb | default(false) | bool

- name: Add node vm's to init_vns
  ansible.builtin.set_fact:
    init_vms: "{{ init_vms + ['bootstrap'] + prepare_masters + prepare_workers }}"
    clean_lab: true
  when: init_cluster | default(false) | bool

- name: Make the init_vm unique items only
  ansible.builtin.set_fact:
    init_vms: "{{ init_vms | unique }}"
