- name: Set init all
  ansible.builtin.set_fact:
    init_svc: true
    init_lb: true
    init_cluster: true
  when: init_all | default('false') | bool

- name: Ensure init bools are set
  ansible.builtin.set_fact:
    init_cluster: "{{ init_cluster | default(false) }}"
    init_svc: "{{ init_svc | default(false) }}"
    init_lb: "{{ init_lb | default(false) }}"
