- name: Ensure ocp_assetsdir is set
  ansible.builtin.set_fact:
    ocp_assetsdir: "{{ ocp_assetsdir | default(playbook_dir + '/' + cluster) }}"

- name: Ensure init_vms is set
  ansible.builtin.set_fact:
    init_vms: "{{ init_vms | default([]) }}"

- name: Check hosts
  ansible.builtin.include_tasks:
    file: check_hosts.yml

- name: Check the init settings
  ansible.builtin.include_tasks:
    file: check_init.yml

- name: Check init_vm
  ansible.builtin.include_tasks:
    file: check_init_vm.yml

- name: Check the status of the vm's
  ansible.builtin.include_tasks:
    file: check_vm.yml

- name: Ensure enable bootstrap is set
  ansible.builtin.set_fact:
    enable_bootstrap: "{{ hostvars['localhost']['init_cluster'] | default(false) }}"
