- name: Ensure cluster is set
  ansible.builtin.set_fact:
    cluster: "{{ cluster | default('ocp_local') }}"

- name: Load vars from group {{ cluster }}
  ansible.builtin.group_by:
    key: "{{ cluster }}"

- name: Ensure ocp_assetsdir is set
  ansible.builtin.set_fact:
    ocp_assetsdir: "{{ ocp_assetsdir | default(playbook_dir + '/' + cluster) }}"

- name: Ensure enable bootstrap is set
  ansible.builtin.set_fact:
    enable_bootstrap: "{{ hostvars['localhost']['init_cluster'] | default(false) }}"

- name: Check the init settings
  ansible.builtin.include_tasks:
    file: check_init.yml

- name: Check init_vm
  ansible.builtin.include_tasks:
    file: check_init_vm.yml

- name: Check the status of the vm's
  ansible.builtin.include_tasks:
    file: check_vm.yml
