ocp_cluster_name: okd
ocp_networktype: OVNKubernetes
# for details see https://github.com/okd-project/okd/releases
# fedora core-os https://fedoraproject.org/coreos/download?stream=stable#arches
# ocp_coreos_url: https://quay.io/repository/

# ocp_release: 4.16.0-0.okd-scos-2024-09-24-151747
ocp_release: 4.16.0-okd-scos.0
ocp_client_url: https://github.com/okd-project/okd-scos/releases/download/{{ ocp_release }}/openshift-client-linux-{{ ocp_release }}.tar.gz
ocp_install_url: https://github.com/okd-project/okd-scos/releases/download/{{ ocp_release }}/openshift-install-linux-{{ ocp_release }}.tar.gz
ocp_webserver_coreos_path: /network/repo/scos

# local registry url = ocp_local_registry/ocp_local_repository/ocp_release
ocp_product_repo: openshift
ocp_local_repo: "{{ ocp_product_repo }}"
# okd remote registry url = ocp_remote_registry/ocp_product_repo/ocp_release_name:ocp_release
ocp_remote_registry: quay.io


efi_secure_boot: false
