- name: Ensure ssh pub key is set
  ansible.builtin.set_fact:
    ocp_ignition_core_ssh_key: "{{ ocp_ignition_core_ssh_key | default(lookup('file', lookup('ansible.builtin.env', 'HOME') + '/.ssh/id_rsa.pub')) }}"

- name: Check if there already is a configuration
  ansible.builtin.stat:
    path: "{{ ocp_assetsdir }}/auth/kubeconfig"
  register: config_check

- name: Only run these when there is no configuration
  when: not config_check['stat']['exists']
  block:
    - name: Create install-config.yaml
      ansible.builtin.template:
        src: install-config.yaml.j2
        dest: "{{ ocp_assetsdir }}/install-config.yaml"
        mode: "0700"
        owner: "{{ lookup('ansible.builtin.env', 'USER') }}"
        group: "{{ lookup('ansible.builtin.env', 'USER') }}"

    - name: Manifest block
      when: not untill_install_config | default(false) | bool
      block:
        - name: Create manifest files
          ansible.builtin.command: openshift-install create manifests
          args:
            chdir: "{{ ocp_assetsdir }}"
            creates: "{{ ocp_assetsdir }}/manifests"

        - name: Calico block
          when: ocp_ignition_networktype == 'Calico'
          block:
            - name: Download Calico manifests
              ansible.builtin.unarchive:
                src: "{{ ocp_ignition_calico_url }}"
                dest: "{{ ocp_assetsdir }}/manifests"
                extra_opts:
                  - --strip-components=1
                remote_src: true

            - name: Download Calico manifests
              ansible.builtin.copy:
                src: 01-cr-installation.yaml
                dest: "{{ ocp_assetsdir }}/manifests/01-cr-installation.yaml"
                mode: "0644"

        - name: Create ignition files
          ansible.builtin.command: "openshift-install create ignition-configs"
          args:
            chdir: "{{ ocp_assetsdir }}"
            creates: "{{ ocp_assetsdir }}/master.ign"
          when:
            - not untill_manifests | default(false) | bool
