- name: Only run for svc and lb
  when: host['role'] in ['svc', 'loadbalancer']
  block:
    - name: Create tmp dir
      ansible.builtin.tempfile:
        state: directory
      register: ks_tempfile

    - name: Create kickstart
      ansible.builtin.template:
        src: /home/rob/code/lab_ocp/roles/ocp_infra/templates/rocky-9-ks.cfg.j2
        dest: "{{ ks_tempfile['path'] }}/ks.cfg"
        mode: '0644'
        owner: "{{ lookup('ansible.builtin.env', 'USER') }}"

    - name: Create kickstart iso
      ansible.builtin.command: >-
        genisoimage -output {{ ocp_infra_libvirt_storage_location }}/{{ host['name'] }}-ks.iso -volid OEMDRV -joliet -rock {{ ks_tempfile['path'] }}/ks.cfg
      tags:
        - skip_ansible_lint
      vars:
        ansible_user: root
    #    ansible_connection: ssh

    - name: Clean up tmp dir
      ansible.builtin.file:
        path: "{{ ks_tempfile['path'] }}/ks.cfg"
        state: absent

    - name: Download rocky iso
      ansible.builtin.get_url:
        url: "{{ ocp_infra_rocky_iso_url }}"
        dest: "{{ ocp_infra_libvirt_storage_location }}/{{ (ocp_infra_rocky_iso_url | ansible.builtin.split('/'))[-1] }}"
        mode: "0644"
      vars:
        ansible_user: root
    #    ansible_connection: ssh
