- name: Delete kickstart iso
  ansible.builtin.file:
    path: "{{ ocp_infra_libvirt_storage_location }}/{{ host['name'] }}-ks.iso"
    state: absent
  vars:
    ansible_user: root
  when: host['role'] in ['svc', 'loadbalancer']

#    ansible_connection: ssh
