- name: Delete ocp directory
  ansible.builtin.file:
    path: "{{ lookup('ansible.builtin.env', 'HOME') }}/{{ cluster }}"
    state: absent

- name: Create ocp directory
  ansible.builtin.file:
    path: "{{ lookup('ansible.builtin.env', 'HOME') }}/{{ cluster }}"
    mode: "0700"
    state: directory
