- name: Delete the iso's
  ansible.builtin.include_tasks:
    file: delete_iso.yml
  loop: "{{ ocp_infra['hosts'] }}"
  loop_control:
    loop_var: host
  when:
    - host['role'] == 'svc'
    - host['role'] in include_roles

- name: Create the iso's
  ansible.builtin.include_tasks:
    file: create_iso.yml
  loop: "{{ ocp_infra['hosts'] }}"
  loop_control:
    loop_var: host
  when:
    - host['role'] == 'svc'
    - host['role'] in include_roles
