- name: Set roles to include
  ansible.builtin.set_fact:
    include_roles: "{{ ocp_infra_init_svc | default(false) | bool | ternary('[`svc`]', '[`master`, `worker`, `bootstrap`]') }}"

- name: Delete ocp directory
  ansible.builtin.file:
    path: "{{ lookup('ansible.builtin.env', 'HOME') }}/{{ cluster }}"
    state: absent
  when: init_cluster | default(false) | bool

- name: Create ocp directory
  ansible.builtin.file:
    path: "{{ lookup('ansible.builtin.env', 'HOME') }}/{{ cluster }}"
    mode: "0700"
    state: directory

- name: Delete the iso's
  ansible.builtin.include_tasks:
    file: delete_iso.yml
  loop: "{{ ocp_infra['hosts'] }}"
  loop_control:
    loop_var: host
  when:
    - host['role'] == 'svc'
    - host['role'] in include_roles

- name: Create the iso's
  ansible.builtin.include_tasks:
    file: create_iso.yml
  loop: "{{ ocp_infra['hosts'] }}"
  loop_control:
    loop_var: host
  when:
    - host['role'] == 'svc'
    - host['role'] in include_roles

- name: Delete vm
  ansible.builtin.include_tasks:
    file: delete_vm.yml
  loop: "{{ ocp_infra['hosts'] }}"
  loop_control:
    loop_var: host
  when: host['role'] in include_roles

- name: Create vm
  ansible.builtin.include_tasks:
    file: create_vm.yml
  loop: "{{ ocp_infra['hosts'] }}"
  loop_control:
    loop_var: host
  when: host['role'] in include_roles
