- name: Set the run value for all the nodes
  ansible.builtin.include_tasks:
    file: run.yml
  run_once: true

- name: Setup the dir's
  ansible.builtin.include_tasks:
    file: dir.yml
  run_once: true
  when: init_cluster | default(false) | bool

- name: Setup the iso's
  ansible.builtin.include_tasks:
    file: iso.yml
  loop: "{{ ocp_infra['hosts'] }}"
  loop_control:
    loop_var: host

- name: Setup vm's
  ansible.builtin.include_tasks:
    file: vm.yml
  loop: "{{ ocp_infra['hosts'] }}"
  loop_control:
    loop_var: host
