- name: Set roles to include
  ansible.builtin.set_fact:
    include_roles: "{{ ocp_infra_init_svc | default(false) | bool | ternary('[`svc`]', '[`master`, `worker`, `bootstrap`]') }}"

- name: Setup the iso's
  ansible.builtin.include_tasks:
    file: dir.yml

- name: Setup the iso's
  ansible.builtin.include_tasks:
    file: iso.yml

- name: Setup vm's
  ansible.builtin.include_tasks:
    file: vm.yml
