- name: Ensure init_vms is set
  ansible.builtin.set_fact:
    init_vms: "{{ init_vms | default([]) }}"

- name: Add svc to init_vms
  ansible.builtin.set_fact:
    init_vms: "{{ init_vms + ['svc'] }}"
  when: init_svc | default(false) | bool

- name: Add lb to init_vms
  ansible.builtin.set_fact:
    init_vms: "{{ init_vms + ['lb'] }}"
  when: init_lb | default(false) | bool

- name: Add cluster nodes to init_vms
  ansible.builtin.set_fact:
    init_vms: "{{ init_vms + ['master01', 'master02', 'master03', 'worker01', 'worker02', 'bootstrap'] }}"
  when: init_cluster | default(false) | bool
