- name: Install haproxy
  ansible.builtin.package:
    name: haproxy
    state: present
  when: "'haproxy' not in ansible_facts['packages'].keys()"

- name: Configure haproxy
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: "0644"
  notify:
    - Restart haproxy
