- name: Delete ocp directory
  ansible.builtin.file:
    path: "{{ ocp_assetsdir }}"
    state: absent
  when: init_cluster | default(false) | bool

- name: Create ocp directory
  ansible.builtin.file:
    path: "{{ ocp_assetsdir }}"
    mode: "0700"
    state: directory
