- name: Setup ocp dir
  ansible.builtin.include_tasks:
    file: dir.yml

- name: Check binaries
  ansible.builtin.include_tasks:
    file: check_ocp_binaries.yml

- name: Download binaries
  ansible.builtin.include_tasks:
    file: download_ocp_binaries.yml
