allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: synology-iscsi-storage
parameters:
  fsType: xfs
provisioner: csi.san.synology.com
reclaimPolicy: Retain
volumeBindingMode: Immediate
